### ISSUE TITLE
ModelServerClient.getAll() has compile-time type (string | string[]) but different runtime type (object).

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver-theia#20]
As mentioned on Spectrum [1] the `getAll` of the client has an incorrect return type and should return a map-like structure that maps from file URI to object.

[1] https://spectrum.chat/emfcloud/modelserver/modelserverclient-getall-has-compile-time-type-string-string-but-different-runtime-type-object~f85ffe9d-1639-4bb4-9f01-6b600d9bf626

**Comment by hoelzl-florian** [comment]
I suggest to introduce a wrapper object that resembles EMF's Resource class, like this:
{
  modelUri : string,
  eContent : object[]
}
Then getAll() simply returns an array of these objects and everybody can access each model's URI and content statically.
This abolishes any use of Object.entries or Object.keys on the result of getAll().
