### ISSUE TITLE
Introduce FileWatcher concept to notify the Model Server about file changes

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver-theia#50]
At the moment, if resources are manipulated via Theia's default editors (without sending any commands), the Model Server is not notified about file changes.
We should introduce a FileWatcher concept (e.g. listening to file changes and Theia's FileOperations `{ CREATE, DELETE, MOVE, COPY }`) to notify the Model Server. Some default requests are already available in in the `model-server-api.ts`, and it should be extended by the remaining requests (e.g. `addResource`, `renameResource` and so on).

As a first step, we customized the Theia `WorkspaceDeleteHandler` in the ecore-glsp editor to be able to properly remove resources from the Model Server (see also https://github.com/eclipse-emfcloud/ecore-glsp/pull/96).

**Comment by CamilleLetavernier** [comment]
IMO Theia should not be involved in this. The ModelServer should be able to listen to file changes directly, regardless of which clients are using it, and have a strategy for reconciling (Essentially: either keep the in-memory model and ignore file-system changes, or reload from file system)

**Comment by ndoschek** [comment]
Thanks, I agree! Closing in favour of https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/115
