### ISSUE TITLE
Provide standalone modelserver-client

### ISSUE THREAD

**Issue by tortmayr** [eclipse-emfcloud/emfcloud-modelserver-theia#65]
Currently the model-server client API is nested into the `modelserver-theia` package and cannot be used in a context without Theia.
AFAIK the model-server client doesn't have any direct Theia dependencies and could be provided in a separate package which facilitates reusing it in a non-Theia application e.g. a plain node back-end.

This is also a good opportunity to discuss the overall architecture of the model-server client.
Currently a simple, custom rest client is used under the hood. While this client suffices to cover the basic usecases it has a couple of downsides:
- The simple rest client is only working In a node context which limits the reuseability of the model server client as a whole. From a technical point of view there is no real reason for this limitation. Both REST & Websocket work perfectly fine in the browser.
- The simple rest client as no exception handling concept e.g. throwing an error if a response with status code >200 is received. This forces us to expose low-level response objects via the ModelServer Client API & delegates the exception handling to API uses. With a sophisticated exception handling concept the ModelServer API could directly return the concrete data objects instead of the low level response.
- There is no way to unit test the ModelServer Client API because a mocking framework for the simple rest client would be required.

I think most of these issues could be resolved by switching to a well-established rest client library like [axios](https://www.npmjs.com/package/axios). There are also mocking frameworks available for axios which means unit tests could be implemented relativity easy.

We need to be careful with the handling of websockets be able to use the model serve client in both node & browser context. An isomorphic implementation that works in both contexts should be used.

We (EclipseSource) intend to contribute this on behalf of ST Microelectronics.

**Comment by ndoschek** [comment]
Fixed with #69
