### ISSUE TITLE
Wrong subscription path calculation

### ISSUE THREAD

**Issue by agonzalezgaliana** [eclipse-emfcloud/emfcloud-modelserver-theia#99]
Hi all!

I'm coming from [here](https://github.com/eclipse-emfcloud/emfcloud/discussions/154).

Basically I'm not able to subscribe to events from the Model Server. Taking a look to the requests in the Model Server side I was able to identify a wrong request to the `subscribe` method (`localhost:8081/api/v1subscribe` missing a `'/'`).

Taking a look to the code of the `v1` client I was able to see that the `model-server-client.ts` has the method `createSubscriptionPath` which does not explicitly insert the `'/'`. However, the `model-server-client-v2.ts` has the same method which actually inserts the missing `'/'` character.

Could perhaps someone take a look on it and verify if this is actually a bug?

Kind regards.

**Comment by martin-fleck-at** [comment]
Hi @agonzalezgaliana! Thank you very much for raising this. We will investigate this and try to fix that soon.
